insert into productos (nombre, descripcion, precio, stock) values ('Hettie', 'Vila do Mosteiros', 22, 7);
insert into productos (nombre, descripcion, precio, stock) values ('Mac', 'Arthur''s Town', 33, 3);
insert into productos (nombre, descripcion, precio, stock) values ('Rowan', 'Koro Island', 81, 3);
insert into productos (nombre, descripcion, precio, stock) values ('Babette', 'Groningen', 49, 1);
insert into productos (nombre, descripcion, precio, stock) values ('Iorgo', 'Nanchong', 49, 4);
insert into productos (nombre, descripcion, precio, stock) values ('Amery', 'Kapolei', 12, 3);
insert into productos (nombre, descripcion, precio, stock) values ('Keely', 'Ensenada', 75, 1);
insert into productos (nombre, descripcion, precio, stock) values ('Starr', 'Malolo Lailai Island', 79, 10);
insert into productos (nombre, descripcion, precio, stock) values ('Kissie', 'Namatanai', 70, 8);
insert into productos (nombre, descripcion, precio, stock) values ('Sena', 'soto', 93, 10);
insert into productos (nombre, descripcion, precio, stock) values ('ina', 'San Juan Aposento', 55, 5);
insert into productos (nombre, descripcion, precio, stock) values ('Matthew', 'Surin', 74, 5);
insert into productos (nombre, descripcion, precio, stock) values ('Nobe', 'ColÃ³n', 28, 3);
insert into productos (nombre, descripcion, precio, stock) values ('Thor', 'Marathon', 67, 4);
insert into productos (nombre, descripcion, precio, stock) values ('Levy', 'soto', 24, 9);
insert into productos (nombre, descripcion, precio, stock) values ('Hillie', 'Palm Springs', 45, 8);
insert into productos (nombre, descripcion, precio, stock) values ('Ginnie', 'Changzhi', 40, 3);
insert into productos (nombre, descripcion, precio, stock) values ('Kris', 'Drumduff', 77, 6);
insert into productos (nombre, descripcion, precio, stock) values ('Erskine', 'Saumlaki-Yamdena Island', 30, 1);
insert into productos (nombre, descripcion, precio, stock) values ('Mendy', 'Negage', 100, 3);
insert into productos (nombre, descripcion, precio, stock) values ('Al', 'Tumbes', 60, 9);
insert into productos (nombre, descripcion, precio, stock) values ('Milo', 'Atiu Island', 71, 3);
insert into productos (nombre, descripcion, precio, stock) values ('Antonella', 'St Catharines', 47, 6);
insert into productos (nombre, descripcion, precio, stock) values ('Alberik', 'Saransk', 95, 7);
insert into productos (nombre, descripcion, precio, stock) values ('Hadria', 'Falmouth', 100, 9);
insert into productos (nombre, descripcion, precio, stock) values ('Warren', 'Kobuk', 39, 4);
insert into productos (nombre, descripcion, precio, stock) values ('Chrisse', 'Doncaster', 93, 9);
insert into productos (nombre, descripcion, precio, stock) values ('Kristopher', 'soto', 13, 9);
insert into productos (nombre, descripcion, precio, stock) values ('Eamon', 'Augsburg', 78, 3);
insert into productos (nombre, descripcion, precio, stock) values ('Leelah', 'Rock Sound', 79, 1);
insert into productos (nombre, descripcion, precio, stock) values ('Nicoli', 'Artigas', 24, 9);
insert into productos (nombre, descripcion, precio, stock) values ('Boote', 'Concordia', 6, 6);
insert into productos (nombre, descripcion, precio, stock) values ('Ariana', 'Fairbanks/Ft Wainwright', 88, 2);
insert into productos (nombre, descripcion, precio, stock) values ('Berri', 'Dillon''s Bay', 3, 5);
insert into productos (nombre, descripcion, precio, stock) values ('Ingram', 'Lucas do Rio Verde', 96, 4);
insert into productos (nombre, descripcion, precio, stock) values ('Elsey', 'Macon', 4, 7);
insert into productos (nombre, descripcion, precio, stock) values ('Renelle', 'Fayetteville', 24, 8);
insert into productos (nombre, descripcion, precio, stock) values ('Lilyan', 'Tianjin', 14, 4);
insert into productos (nombre, descripcion, precio, stock) values ('Ivor', 'Bali', 64, 2);
insert into productos (nombre, descripcion, precio, stock) values ('Christian', 'Maripasoula', 30, 2);
insert into productos (nombre, descripcion, precio, stock) values ('Colette', 'San Juan Del CÃ©sar', 73, 10);
insert into productos (nombre, descripcion, precio, stock) values ('Carl', 'Resolute Bay', 57, 6);
insert into productos (nombre, descripcion, precio, stock) values ('Allis', 'soto', 80, 8);
insert into productos (nombre, descripcion, precio, stock) values ('Othella', 'Myroodah', 33, 1);
insert into productos (nombre, descripcion, precio, stock) values ('Theodora', 'soto', 93, 5);
insert into productos (nombre, descripcion, precio, stock) values ('Cassie', 'Ninglang', 63, 7);
insert into productos (nombre, descripcion, precio, stock) values ('Timoteo', 'Gorno-Altaysk', 28, 2);
insert into productos (nombre, descripcion, precio, stock) values ('Tana', 'Poitiers/Biard', 5, 5);
insert into productos (nombre, descripcion, precio, stock) values ('Amitie', 'soto', 87, 2);
insert into productos (nombre, descripcion, precio, stock) values ('Rockwell', 'Borba', 46, 9);
insert into productos (nombre, descripcion, precio, stock) values ('Chad', 'San Jose', 3, 2);
insert into productos (nombre, descripcion, precio, stock) values ('Leola', 'Kurundi Station', 75, 7);
insert into productos (nombre, descripcion, precio, stock) values ('Lynnelle', 'Roswell', 8, 10);
insert into productos (nombre, descripcion, precio, stock) values ('Karlene', 'Brussels', 17, 8);
insert into productos (nombre, descripcion, precio, stock) values ('Ramonda', 'San Antonio Oeste', 6, 5);
insert into productos (nombre, descripcion, precio, stock) values ('Ariadne', 'Liangia', 94, 4);
insert into productos (nombre, descripcion, precio, stock) values ('Antonius', 'Saint-Ã‰tienne/BouthÃ©on', 67, 1);
insert into productos (nombre, descripcion, precio, stock) values ('Rhody', 'Pierre', 6, 10);
insert into productos (nombre, descripcion, precio, stock) values ('Kerri', 'Zhengzhou', 80, 4);
insert into productos (nombre, descripcion, precio, stock) values ('Cherye', 'JoÃ£o Pessoa', 53, 9);
insert into productos (nombre, descripcion, precio, stock) values ('Birdie', 'Afyonkarahisar', 93, 10);
insert into productos (nombre, descripcion, precio, stock) values ('Noelani', 'Provce', 11, 6);
insert into productos (nombre, descripcion, precio, stock) values ('Suellen', 'Merluna', 55, 7);
insert into productos (nombre, descripcion, precio, stock) values ('Frederic', 'Belaga', 59, 5);
insert into productos (nombre, descripcion, precio, stock) values ('Fin', 'Karasabai', 83, 2);
insert into productos (nombre, descripcion, precio, stock) values ('Dania', 'Lagrange', 73, 3);
insert into productos (nombre, descripcion, precio, stock) values ('Linn', 'Zakynthos Island', 23, 3);
insert into productos (nombre, descripcion, precio, stock) values ('Ondrea', 'soto', 22, 10);
insert into productos (nombre, descripcion, precio, stock) values ('Nickolai', 'Locarno', 23, 8);
insert into productos (nombre, descripcion, precio, stock) values ('Shela', 'Gatineau', 51, 6);
insert into productos (nombre, descripcion, precio, stock) values ('Tiffani', 'Wasilla', 33, 6);
insert into productos (nombre, descripcion, precio, stock) values ('Petronilla', 'Liupanshui', 61, 4);
insert into productos (nombre, descripcion, precio, stock) values ('Marci', 'Bulgan', 24, 5);
insert into productos (nombre, descripcion, precio, stock) values ('Morna', 'Amboin', 56, 1);
insert into productos (nombre, descripcion, precio, stock) values ('Chance', 'Kerama', 44, 8);
insert into productos (nombre, descripcion, precio, stock) values ('Letitia', 'Grants Pass', 33, 7);
insert into productos (nombre, descripcion, precio, stock) values ('Marty', 'KÃ©dougou', 88, 9);
insert into productos (nombre, descripcion, precio, stock) values ('Eberhard', 'Erechim', 94, 1);
insert into productos (nombre, descripcion, precio, stock) values ('Jobie', 'La MÃ´le', 90, 3);
insert into productos (nombre, descripcion, precio, stock) values ('Marybeth', 'Ilulissat', 87, 4);
insert into productos (nombre, descripcion, precio, stock) values ('Cecilla', 'Stara Zagora', 21, 10);
insert into productos (nombre, descripcion, precio, stock) values ('Ransom', 'Anatom Island', 13, 3);
insert into productos (nombre, descripcion, precio, stock) values ('Belle', 'Williams Lake', 78, 6);
insert into productos (nombre, descripcion, precio, stock) values ('Kennett', 'CassilÃ¢ndia', 76, 2);
insert into productos (nombre, descripcion, precio, stock) values ('Cherie', 'Moscow', 4, 8);
insert into productos (nombre, descripcion, precio, stock) values ('Gerhardt', 'Lhok Sukon-Sumatra Island', 51, 8);
insert into productos (nombre, descripcion, precio, stock) values ('Brose', 'Clearwater', 4, 2);
insert into productos (nombre, descripcion, precio, stock) values ('Donall', 'Lyons', 32, 5);
insert into productos (nombre, descripcion, precio, stock) values ('Kris', 'Sacramento', 75, 8);
insert into productos (nombre, descripcion, precio, stock) values ('Ianthe', 'Pica', 11, 8);
insert into productos (nombre, descripcion, precio, stock) values ('Fania', 'Lathrop', 28, 7);
insert into productos (nombre, descripcion, precio, stock) values ('Marilee', 'Rapity', 31, 8);
insert into productos (nombre, descripcion, precio, stock) values ('Dulcine', 'Bubaque', 30, 2);
insert into productos (nombre, descripcion, precio, stock) values ('Marla', 'Skopje', 81, 1);
insert into productos (nombre, descripcion, precio, stock) values ('Cal', 'Jixi', 9, 5);
insert into productos (nombre, descripcion, precio, stock) values ('Anestassia', 'Richard Toll', 88, 4);
insert into productos (nombre, descripcion, precio, stock) values ('Wyn', 'Lesobeng', 62, 7);
insert into productos (nombre, descripcion, precio, stock) values ('Stanwood', 'Beihai', 12, 2);
insert into productos (nombre, descripcion, precio, stock) values ('Darrell', 'Puerto Limon', 11, 9);
insert into productos (nombre, descripcion, precio, stock) values ('Burtie', 'Broken Hill', 19, 3);